apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-microservice
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-microservice
  template:
    metadata:
      labels:
        app: sample-microservice
    spec:
      containers:
      - name: microservice
        image: bus57790/sample-microservice:556-20260825-160409
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-microservice
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: sample-microservice
