apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-simple-app
  template:
    metadata:
      labels:
        app: argocd-simple-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: argocd-simple-app
          image: ghcr.io/bus57790/argocd-simple-app:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5
